Repository nitendra2211/SignIn-Page, pull requests merged in 2024-10, with the labels that each got.

#7 Update style.css
  style.css
Labels: good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024

#10 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024, level3

#11 Forgot password page added
  forgot_password.html
  index.html
Labels: good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024, level3

#15 Update README.md
  README.md
Labels: good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024

#14 improved readme.md file
  README.md
Labels: good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024, level3

#17 [FEAT]: Implement Dark and Light Modes for the webpage #13
  forgot_password.html
  index.html
  script.js
  style.css
Labels: enhancement, good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024, level3

#19 Update README.md
  README.md
Labels: enhancement, good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024

#20 Update README.md
  README.md
Labels: good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024

#21 Added Password Strength checking functionality
  index.html
  script.js
Labels: hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024, level3

#24 Device Detection and Auto Sign-In Suggestion
  index.html
  script.js
Labels: enhancement, good first issue, hactoberfest-accepted, hactoberfest, girlscript-ext, hacktoberfest2024, level3
